apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: ir1
  namespace: ace
spec:
  createDashboardUsers: true
  adminServerSecure: true
  env:
    - name: MQSI_OVERRIDE_HOSTNAME
      value: 'ir1-is.ace.svc'
    - name: MQSI_OVERRIDE_HTTPS_PORT
      value: '443'
  license:
    accept: true
    license: L-KZVS-2G3FW4
    use: CloudPakForIntegrationNonProduction
  telemetry:
    tracing:
      openTelemetry:
        enabled: true
  template:
    spec:
      containers:
        - resources:
            limits:
            cpu: '0.5'
            memory: 1Gi
          requests:
            cpu: '0.5'
            memory: 1Gi
          name: runtime
  logFormat: basic
  barURL: 'https://db-dash-dash:3443/v1/directories/ivt2?99b0009e-fecd-4489-94c7-56fa03793832'
  configurations: ["mqpolicy", "key.jks", "kafkapolicy", "httpsconf"]
  version: '12.0'
  replicas: 1
