apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationRuntime
metadata:
  name: ir1
  namespace: ace
spec:
  license:
    accept: true
    license: L-MJTK-WUU8HE
    use: CloudPakForIntegrationNonProduction
  telemetry:
    tracing:
      openTelemetry:
        enabled: true
  template:
    spec:
      containers:
        - resources:
            limits:
            cpu: '0.5'
            memory: 1Gi
          requests:
            cpu: '0.5'
            memory: 1Gi
          name: runtime
  logFormat: basic
  barURL:
    - >-
      https://db-01-quickstart-dash:3443/v1/directories/Backend?6b0f9d35-c4cf-41c3-a541-8c6beb47dda1
  configurations: ["mqpolicy", "key.jks", "kafkapolicy", "httpsconf", "scramparms", "es-cert-ace.jks"]
  version: '12.0'
  replicas: 1
